### ISSUE TITLE
Does not detect any sound playing from Macbook Pro

### ISSUE THREAD

**Issue by YvanQ** [kritzikratzi/Oscilloscope#1]
It does detect input from the microphone. I'm running the program on a 2014 Retina Macbook Pro running Yosemite. The sound devices all show up, but it does not detect the sound running out of any of them.

**Comment by kritzikratzi** [comment]
hey! 

yep, that's a problem with the device-list. it should only display the input devices (like microphone/line in, etc.).
on a mac you _cannot_ directly capture the master output unfortunately. 


the common solution involves a few steps: 

To set everything up (only once): 
1. download and install soundflowe. restart your mac. 
2. open "audio-midi-setup" (just search it using spotlight, its on every mac). 
3. click "+" in the bottom left, then "create multi output device"
4. now enable the checkboxes for "Output (built-in)" and "Soundflower (2ch)"
5. Rename that new device to "Loop Output", or something like that. 


And then to use it: 
1. Start playing the thing. Adjust the volume to a nice level
2. Alt+Click on the speaker icon, top right in the menu bar. Select "Loop Output" or whatever you named the thing. 
3. Start the oscilloscope application, select "Soundflower (2ch)" as input device.

**Comment by YvanQ** [comment]
Your solution worked perfectly, thanks!

**Comment by kritzikratzi** [comment]
https://github.com/kritzikratzi/Oscilloscope/issues/2
