### ISSUE TITLE
improve afterglow

### ISSUE THREAD

**Issue by kritzikratzi** [kritzikratzi/Oscilloscope#10]
i suppose afterglow could be hugely improved by using a different approach: 
instead of drawing ontop of the old frame, keep a bunch of past buffers in vbos, and draw those with increasing darkness from past to present. 

this should look vastly better than the current approach.

**Comment by wraybowling** [comment]
Keeping a bunch of vbos would use a lot more memory. Maybe instead, keep just one extra vbo to keep exposure/gamma information which you can dial down along with brightness.

(Also, fwiw, I think it looks great as is.)

**Comment by kritzikratzi** [comment]
leaving it as is :)
