### ISSUE TITLE
virustotal detected

### ISSUE THREAD

**Issue by zagk** [kritzikratzi/Oscilloscope#15]
https://www.virustotal.com/en/file/3733dbd522282d94c05fd24b089195700bf792765eb6151dd8a5ee211a31f421/analysis/1480216080/

Ikarus 	PUA.Multiplug

**Comment by kritzikratzi** [comment]
it's a false positive. not sure what i can do.

**Comment by kritzikratzi** [comment]
there's nothing i can do :(
