### ISSUE TITLE
geometry shader extension (gl_ext_geometry_shader4) not available

### ISSUE THREAD

**Issue by Abubakr95** [kritzikratzi/Oscilloscope#17]
On a windows 10 x64-bit machine ... Don't know what to do

**Comment by kritzikratzi** [comment]
i will look into this very very soon, because it seems to concern many people!

**Comment by xmescu** [comment]
please do it!

**Comment by kritzikratzi** [comment]
i'm quite sure i fixed it today, but i haven't tested on windows yet. binary will be out sat or sunday (not sure if i have time tomorrow)

**Comment by xmescu** [comment]
Ok. I'm waiting for a response  Saturday, 10 December 2016, 04:23AM +00:00 from hansi raber  notifications@github.com :

**Comment by kritzikratzi** [comment]
can you try this and please let me know? https://asdfg.me/up/Oscilloscope-1.0.6-win32-pre.zip

**Comment by eumunhoz** [comment]
doesn't open on my windows 10 x64-bit

**Comment by kritzikratzi** [comment]
can you describe a bit more in detail? 
do you get any kind of error or other message?

**Comment by eumunhoz** [comment]
I run the .exe file, then it loads a litte but doesn't show anything

**Comment by kritzikratzi** [comment]
is it still open if you look for oscilloscope.exe in the task manager?

**Comment by eumunhoz** [comment]
in the task manager the oscilloscope.exe shows for some seconds then disappear

**Comment by xmescu** [comment]
I will attach a screenshot of the error.

**Comment by Abubakr95** [comment]
💃 it works on my machine (WIN 10 pro, Build 10586) thanks a lot  .. it's a little buggy though, anything that refreshes the display causes the sound to crackle .. and attempting to minimize the exe makes it stop working

**Comment by FelipeTesta** [comment]
Windows 7 32 bits. "geometry shader extension (gl_ext_geometry_shader4) not available".

**Comment by kritzikratzi** [comment]
@FelipeTesta yes, that's an old version. can you test this please: https://asdfg.me/up/Oscilloscope-1.0.6-win32-pre.zip

**Comment by FelipeTesta** [comment]
Nice! That's working.

**Comment by kritzikratzi** [comment]
@FelipeTesta great. can you please test: 

- minimizing the app
- dragging a lot of different files into it (wav, mp3, mp4, avi, ... whatever you can find). 

does it crash doing any of that?

**Comment by FelipeTesta** [comment]
Minimizing and fullscreen mode is working.

I don't have all this types of archive right now, but I'll soon. When I get these I'll try.

**Comment by kritzikratzi** [comment]
geometry shader seems fixed.
