### ISSUE TITLE
Linear mode with adjustable speeds and sync

### ISSUE THREAD

**Issue by wraybowling** [kritzikratzi/Oscilloscope#18]
Not all signals are going to produce pretty pictures. I think this would make an excellent regular scope given its attention to detail and aesthetics. But we need a way to switch to that mode and a slider for setting speed.

Optionally, on real scopes, you can set a different signal to sync to. That'd be nice. Say, use the left channel as sound source and right channel as sync, or vice versa.

**Comment by kritzikratzi** [comment]
speed adjustment is there in the code, just not released yet. 

can you explain the sync more? (you mean a trigger?) 
this is meant as a xy scope, so a trigger isn't really necessary.

**Comment by wraybowling** [comment]
Yes, after looking up the term, I mean a trigger. From using it, I can tell that this is an XY scope. That much is obvious. What I'm asking though is... could it also be a traditional oscilloscope? Otherwise the name of the app and the screenshot on the home page are kind of misleading.

**Comment by kritzikratzi** [comment]
yes, you have a point there. maybe i'll add trigger support one day (there is mono channel support if you compile it yourself), maybe i'll rename it to xy-oscilloscope. who knows what the future will bring :)

**Comment by kritzikratzi** [comment]
mono mode is relased now (happens automatically when you have only one channel in the audio file). 

i'll close this bug for now, everything else you mentioned is a bit out of scope for a bugfix (code contributions as PRs are welcome)
