### ISSUE TITLE
No picture, except a single pixel. 

### ISSUE THREAD

**Issue by kritzikratzi** [kritzikratzi/Oscilloscope#19]
For some people the application starts, plays sound, but only a single pixel is visible in the top left corner. No other output.

**Comment by RomajiQuadhash** [comment]
For me, not even a pixel is displayed

**Comment by risteristevski** [comment]
I also have a single flickering white pixel at the top left position of the window. It's white only when there is sound playing though the application.
Can help with providing you more info if needed.

**Comment by kritzikratzi** [comment]
here is a test build, does this work for you? https://asdfg.me/up/Oscilloscope-1.0.6-win32-pre.zip

**Comment by RomajiQuadhash** [comment]
Thank you very much. This build works perfectly for me

**Comment by kritzikratzi** [comment]
great! happy to finally close this :)

**Comment by risteristevski** [comment]
Works like a charm.
