### ISSUE TITLE
High contrast theme causes GUI to disappear

### ISSUE THREAD

**Issue by cyber199** [kritzikratzi/Oscilloscope#22]
Hello,
I have a laptop running Windows 8.1 with a customised high contrast theme.  When using high contrast mode the interface to control playback and settings disappears (or possibly goes black).

**Comment by kritzikratzi** [comment]
hi! 
can you save&upload your custom theme so i can use the same for testing?

**Comment by cyber199** [comment]
This is the theme I use mostly (I find it easier to look at than white) however, I recently discovered that this problem could be due to my graphics driver.  I have an HP 250 G4, which apparently uses a custom version of Intel's HD Graphics driver, and there have been others with similar issues caused by using high contrast or classic themes with other programs.

Still, I've zipped up the "save for sharing" file in case you can reproduce it.
[Grey.zip](https://github.com/kritzikratzi/Oscilloscope/files/694387/Grey.zip)

**Comment by kritzikratzi** [comment]
hi! 

thanks for the zip! 

* do you the intel hd variant? (the laptop also exists with an amd card). 
* does the software work when you have your high contrast theme off? 

but yea, the some older versions of intel HD have been a nightmare to handle.

**Comment by cyber199** [comment]
There is an icon for Intel HD in the tray and accompanying control panel program.
It works perfectly with the standard theme.
For reference, the driver version according to the settings is 10.18.14.4112 and the graphics processor is an HD Graphics 5500.

**Comment by kritzikratzi** [comment]
closing because it's too long ago (in the hopes some driver update fixed this)
