### ISSUE TITLE
[Windows] [UI] controls never hide with mouse hovering the window

### ISSUE THREAD

**Issue by Juesto** [kritzikratzi/Oscilloscope#23]
Whenever i hover the mouse in the window the UI refuses to disappear, TAB only helps for 1ms
holding tab just fast-switches the ui hide/show state
Fullscreen is unusable this way, i had to use screen extension to be able to get the mouse outside the window scope

**Comment by kritzikratzi** [comment]
did you move the mouse outside the player controls? (e.g. in the top center)

**Comment by Juesto** [comment]
Yes
Just tested now that borders do not apply, only inside the rendering area (inner window) is where the bug happens
Windows 7 here

**Comment by Juesto** [comment]
Note: This is partially fixed in 1.0.8 but has some bugs still, such as rarely not hiding when the cursor is on top of the window
