### ISSUE TITLE
[Playback] Sluggish visualization when playing FLAC

### ISSUE THREAD

**Issue by Juesto** [kritzikratzi/Oscilloscope#24]
while it can play more formats than WAV (AFAIK, i only tried FLAC) it doesn't render a consistent visual. it keeps muting **(not exactly audio mute)** every 1ms (dot flashing on the screen) and also it renders in a sluggish manner (likely lots of drops)

**Comment by kritzikratzi** [comment]
please press 'i'. then you see a little "drop" counter in the top left. 
does it increase?

**Comment by Juesto** [comment]
Now at least i noticed no dot for some reason but Dropped did increase and visualization is sluggish despite having 60 fps. i also seem to have a constant drop when using microphone (stereo mix) regardless of rendering.
I just discovered that wav drops too
The focus of this issue is FLAC causing a sluggish rendering... i should open an additional one about drops

**Comment by kritzikratzi** [comment]
can you upoad your file for testing? 
also: what's your graphics card?

**Comment by Juesto** [comment]
NVIDIA GeForce GTX 760 and Realtek HDA

Settings i use (Tried forced ansio once and broken sound): 
![image](https://cloud.githubusercontent.com/assets/12691160/21914984/9066d67e-d915-11e6-97af-4e6a880f0ed9.png)

**Comment by Juesto** [comment]
Any FLAC will do, i tried oscillofun

**Comment by kritzikratzi** [comment]
hey! 
what if you use 44kHz, 1024 buffer size and 4 buffers?

**Comment by kritzikratzi** [comment]
also: do you get the same problem with older version? (binaries are in the releases tab)

**Comment by Juesto** [comment]
I am not completely sure, i will try using those default(?) settings.
Could having low ram available have an impact?
And about CPU usage.... it might be stalling on a single thread... i'll check with process explorer

**Comment by Juesto** [comment]
in the center you can notice a dot here, thanks to afterglow. (didnt try your settings yet)
![image](https://cloud.githubusercontent.com/assets/12691160/21932374/12d504fa-d97f-11e6-937e-b679ee5f2e19.png)
I experienced a freeze where the slider reverted to the beginning: see bug #25
I also noticed that after leaving the application running for a very long time it eventually breaks; currently only fullscreen was working 100%, when theres no sound actually playing the rendering stops updating.

**Comment by Juesto** [comment]
Okay with settings you asked FLAC does not stutter :+1:

**Comment by kritzikratzi** [comment]
ah, great. 

i think this is possibly completely unrelated to any performance issues, and might just be that your soundcard doesn't actually support 192kHz. if it's the built-in realtek HD, chances are it only supports 48kHz or 96kHz. please check your system audio settings if you can actually set it to 192. if you can't, there's nothing to be done here. (the app can't magically make your computer do things it doesn't support)

**Comment by Juesto** [comment]
Yes i have it set to 192.
The visualization issue I've experienced can also be seen when using time stretch to slow it down.

**Comment by Juesto** [comment]
Maybe you're right.
From this test i can see that the app might be focused on WAV playback rather than FLAC.
Playing Khrậng wav with your settings works perfectly.
Issue #25 is related to when the player is dropping, especially in FLAC.

**Comment by Juesto** [comment]
hurder mouse (drift face version) seems to have too much complexity for your player to handle, i am having some slight performance issues with it.
i experience no issues when playing with an external player and feeding it to the application with stereo mix

**Comment by Juesto** [comment]
I have verified that only in some instances FLAC playback is sluggish, not always.
other formats are fluid; ogg, wav, mp3.
it's a odd issue.

**Comment by Juesto** [comment]
for the record: my audio is clearly capable of 192khz

**Comment by Juesto** [comment]
Confirmed Fixed in 1.0.8
Apologies for the late response.
