### ISSUE TITLE
[Website misc.] Outdated information

### ISSUE THREAD

**Issue by Juesto** [kritzikratzi/Oscilloscope#26]
Specifically:
- the screenshot in readme.md
- Known Problems in website (most are fixed)

**Comment by kritzikratzi** [comment]
i don't really care about the screenshot on github tbh because it's for programmers only. 
removed the old "known problems" from the website. thanks!

**Comment by Juesto** [comment]
honestly sometimes i wish i could have a ui as simple as the one seen there.

**Comment by Juesto** [comment]
I'd like to know which version is showcased on the screenshots

**Comment by kritzikratzi** [comment]
please be a detective about this yourself. 
find out when the image was put on git, and download the according release.

**Comment by Juesto** [comment]
thanks for your help and time.
