### ISSUE TITLE
[Windows] Drag and Drop does not work to play files

### ISSUE THREAD

**Issue by Juesto** [kritzikratzi/Oscilloscope#27]
I tried dragging a wav file just like it's advertised on the website and it showed the forbidden cursor

**Comment by kritzikratzi** [comment]
and if you drop the file regardless of that, what happens?

**Comment by Juesto** [comment]
nothing

**Comment by kritzikratzi** [comment]
does it work in other applications? can you try googling "windows X drag and drop not working" and see the first few solutions? (put your windows version for X). 

i haven't seen that problem at all on any windows computer yet, and there's not much i can think of that could be done of differently from my point of view. (but who knows...)

**Comment by Juesto** [comment]
Yes, it works with other applications. only yours is having this issue...
I am a freelance technician.

**Comment by Juesto** [comment]
For some reason it wasn't working properly.
I just tried again now and it does work properly.
Odd....

**Comment by Juesto** [comment]
It's weird, it happens rarely but i am not sure how to reproduce this.
i happened to get it blocked after playing oscillofun.
