### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by sleatorgator** [kritzikratzi/Oscilloscope#3]
Tried running the app on OSX 10.10.3 and got this error message

![screen shot 2015-07-30 at 1 52 03 pm](https://cloud.githubusercontent.com/assets/13575885/8990745/3f9b26d8-36c2-11e5-9905-ae008be72eef.png)

**Comment by kritzikratzi** [comment]
yes, this is known and i'm working on it. 
you can try the pre-release i just uploaded: (i didn't want to upload it yet, cause it isn't tested much, but if you're lucky it works) 
https://github.com/kritzikratzi/Oscilloscope/releases/tag/1.0.3-pre

**Comment by sleatorgator** [comment]
Thanks! I'm able to load audio files but can't seem to directly monitor
from my interface.

also, I was amazed to have recently discovered your videos and project! I
am studying computer music at columbia and have been using analog
synthesizers to generate oscillo-art and live visuals. I never realized it
was possible to directly convert images/3d shapes into lissajous waveforms
and was wondering if you could give me some insight as to how the math
works. I have been googling for a few hours and checked out Jerobeams
mushroom patch, but can't seem to find any leads. I would be very grateful
if you could point me in the right direction or perhaps send me a patch to
mess around with.

Isaac

**Comment by kritzikratzi** [comment]
glad it works. 

about your other questions: 
parametric equations are the key. 

once you can view something as a parametric equation, you can convert it to audio easily. if you want to get into that thing, there's no way around them :) 

about monitoring from your interface: yes, this is currently disabled. i think i wrote that down somewhere here: http://asdfg.me/osci/ 

monday release will contain only bugfixes, next step is adding audio input support back in. 
(however, in osx it's impossible to monitor the interface directly, you'll need to use soundflower or a similar audio driver)
