### ISSUE TITLE
[Windows] Crash after changing settings during playback

### ISSUE THREAD

**Issue by Juesto** [kritzikratzi/Oscilloscope#30]
As soon i click "Start!" with something playing it just crashes in a instant, looks like a bug with reinitialization.

**Comment by kritzikratzi** [comment]
can't reproduce. did this happen once, or all the time? 

can you explain more about the circumstances and attach the crash report.

**Comment by Juesto** [comment]
It doesn't crash if you don't change any settings, if you do it does.

**Comment by kritzikratzi** [comment]
cannot reproduce at all on mac, possibly a windows only issue.
