### ISSUE TITLE
[Playback] Compared to previous versions: larger drops and accuracy issue

### ISSUE THREAD

**Issue by Juesto** [kritzikratzi/Oscilloscope#35]
Interestingly enough using the old shader causes a  even larger fps drop than with the current one. its kind of subtle but i do notice some sluggishness.
Now I do not have 60 fps but 58-56fps. drop counter acts differently than before; values jump more in input mode, in playback mode it jumps twice or so. for the record the drop counter was more accurate before
I additionally note a accuracy error with it: playing Blocks in compressed form is drawn incorrectly while it did draw closer to the actual uncompressed audio on the previous version.
Also noticing an odd intensity flickering. like every few moments it flickers, similarly to how it did flicker before particularly with flac playback.
FLAC playback in 192khz now lags less than before

maybe the software requirements were unintentionally increased?

**Comment by kritzikratzi** [comment]
please don't write multiple vague anecodes into a bug report, you are mistaking this for a forum.

**Comment by Juesto** [comment]
Can we chat then please?
i do not have another way to contact you... except maybe email?

**Comment by kritzikratzi** [comment]
please just use the old version. i'm developing this software mostly for myself and i'm giving it out completely for free, including the source code under a very liberal license, and i try to fix most bugs whenever i have time. please don't expect me to work on your wishlist.

**Comment by Juesto** [comment]
Apologies.
I do appreciate your hobby work.
