### ISSUE TITLE
Win32 Binary Issue, Windows 10

### ISSUE THREAD

**Issue by Crystalix007** [kritzikratzi/Oscilloscope#38]
I'm not entirely sure what the cause of this is, however, when running the precompiled binary for release 1.0.8 the program frequently crashes. A heap failure is reported when running the binary. When the program didn't crash, and I attempted to access the settings panel, it immediately crashed.

In trying to debug this myself, compiling for 32 bit on Windows 10, Visual Studio 2015, I also noticed some oddities with memory access exceptions without significant cause.

Having no luck with attempting to debug the program, I tried an attempt to compile for x64 and, surprisingly, the program compiled (having redirected the lib files). Moreover, there was no longer any crashing during load or file open operations. Even more astoundingly, the settings panel opened and worked fine.

I don't quite know which combination of actions made the program work, I just wanted to alert you to the fact that they did.

**Comment by kritzikratzi** [comment]
hey! 

thanks, good to hear. not sure why that is either. changing to 64 soon then :) 
i'll leave this open as a reminder

**Comment by StinkerB06** [comment]
You can still keep win32 binary.

**Comment by kritzikratzi** [comment]
closing because there is no more 32 bit support :)
