### ISSUE TITLE
Repository does not have a license

### ISSUE THREAD

**Issue by eriknstr** [kritzikratzi/Oscilloscope#39]
Readme states only "sourcecode for this application is freely available on github".

Please pick an appropriate license and put the LICENSE file in the root of the repository.

**Comment by Juesto** [comment]
Quoting kritzkratzi:
> i'm developing this software mostly for myself and i'm giving it out completely for free, including the source code under a very liberal license,

A LICENSE is not required, otherwise please point out where it says it's required.

**Comment by Juesto** [comment]
Actually the license is stated in the website: http://asdfg.me/osci

> ### License/Source Code
> 
> -**     You can find the project home and sourcecode freely available on github. The code itself is relased under the WTFPL license.**
> -     Based on Openframeworks, a creative coding library for C++. The larger part of it is licensed as MIT/BSD.
> -     Uses FFmpeg to decode audio files. FFmpeg is licensed under the gpl/lgpl 2.1. The shared libraries included here were compiled to comply with the lgpl. A copy of the LGPL together with instructions how the library was compiled for each platform can be found in the docs/ffmpeg folder that is part of the release files. Alternatively (or if the files were not included by accident) you can find online versions of the compilation instructions and the LGPL as part of the ofxAvCodec project.

**Comment by kritzikratzi** [comment]
thanks! i changed the website to MIT too (not that it makes any difference)

**Comment by eriknstr** [comment]
@Juesto you misunderstood what I meant.

@kritzikratzi thanks for adding license to the repo.

**Comment by Juesto** [comment]
I actually did understood once the license was added. sorry

**Comment by eriknstr** [comment]
Good :)
