### ISSUE TITLE
Windows: Harmless(?) error after a long runtime.

### ISSUE THREAD

**Issue by Juesto** [kritzikratzi/Oscilloscope#40]
randomly when i return to playback mode from input after being in input for long. i get the message, sometimes it hangs but usually it keeps working:![image](https://cloud.githubusercontent.com/assets/12691160/25117217/6dd5247c-23e7-11e7-89c4-e8d6b185307a.png)

**Comment by kritzikratzi** [comment]
funny. 
but never saw it before.

**Comment by Juesto** [comment]
also, clicking OK causes it to terminate. i think
