### ISSUE TITLE
fetching shaders from disk frequently?

### ISSUE THREAD

**Issue by Juesto** [kritzikratzi/Oscilloscope#41]
Apparently there's a point where the visualization begins to freeze.
i notice that during the freeze it's reloading the shaders files from disk (opening then closing), one at a time.

**Comment by kritzikratzi** [comment]
there is a big bug currently 
(when you drag the first file in it's a bit on the lucky side if it's fast enough or spirals into a crash). 

i'm aware of the problem and it's an easy fix, just haven't had time yet.

**Comment by Juesto** [comment]
Actually I've never had such condition. Thanks for the details through!
