### ISSUE TITLE
1.0.8 Windows: Forced ASIO?

### ISSUE THREAD

**Issue by Juesto** [kritzikratzi/Oscilloscope#42]
I have ASIO installed but I am unable to get the standard windows stuff.

Users should be able to choose like before. (batch script)

**Comment by kritzikratzi** [comment]
oh, that must have been an accident. i don't have time to look into it right away, but thanks for reporting it!

**Comment by Juesto** [comment]
or better yet, put both modes together maybe

**Comment by kritzikratzi** [comment]
i stopped supporting asio a while ago
