### ISSUE TITLE
Crash related to audio devices

### ISSUE THREAD

**Issue by Juesto** [kritzikratzi/Oscilloscope#44]
Haven't tested much but, crash conditions so far:
- any invalid/unsupported setting will make it crash
- As soon a device disappears: hang and crash (i can pull the event log if needed)
- A bit unrelated: using input does not release the output.

EDIT: apparently yes. it seems to be a performance issue that isn't anyone's fault!

**Comment by kritzikratzi** [comment]
closing, because selecting sample rate is not gonna be an option anymore
