### ISSUE TITLE
Windows 10, v1.0.8: No Audio Devices show up

### ISSUE THREAD

**Issue by lempamo** [kritzikratzi/Oscilloscope#48]
No input devices, no output devices, nothing.
[Screenshot.](https://user-images.githubusercontent.com/6828076/31592718-568429ae-b1f8-11e7-931f-dd9eeec1e8c6.png)

**Comment by kritzikratzi** [comment]
does 1.0.7 work for you?

**Comment by lempamo** [comment]
Yes, it does, but not 1.0.8

**Comment by Juesto** [comment]
Make sure to remove ASIO if you have it installed. see #42
