### ISSUE TITLE
VST Version?

### ISSUE THREAD

**Issue by XSkid420X** [kritzikratzi/Oscilloscope#49]
i was just wondering if you had the time to make a vst version of this, it'd help out alot.

**Comment by kritzikratzi** [comment]
there is already such a plugin (partially based on this code, actually) by someone else. 
google for soundemote! but it's not free afaik

**Comment by Juesto** [comment]
it's called PrettyScope and it's $20, Soundemote also offers very cool stuff related to oscilloscope music too
