### ISSUE TITLE
Linux version won't open audio card

### ISSUE THREAD

**Issue by kritzikratzi** [kritzikratzi/Oscilloscope#5]
edit: aside, i cant seem to get audio output working on arch. here is the error code:
RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:1,0), Device or resource busy.
it falls between some other HDMI outputs.
this problem could probably be fixed by plugging into pulse/alsa.

**Comment by s-ol** [comment]
@kritzikratzi this is because you probably have PulseAudio running already. Only one process can use alsa at the same time, and PulseAudio is already doing that. It's best to expose the API choice as a parameter at runtime, if thats impossible at build time; otherwise the order of connection should be

- JACK if running
- PulseAudio if running
- ALSA
- OSS

also JACK rules and I wouldn't want to use anything else, especially for the Oscilloscope that presumably wants to display the output of other running processes.

**Comment by s-ol** [comment]
In other news: I'm interested in helping out with this; I would love to have a proper Oscilloscope working that has

- JACK support
- is cross platform so I can advertise using it in workshops etc

On my first attempt just building this against of 0.10 there are some expected issues (API changes like ofFile paths changing from std::string to boost::path) and some completely insane garbage error messages spewing invalid characters and quoting non-ascii source code... something something utf8 and ofxFontAwesome?

**Comment by kritzikratzi** [comment]
hey! 

i'm currently testing to switch over from rtaudio to miniaudio. 
you can take a look in the miniaudio branch. 

if you want a linux version, i would try the following: 

* grab a copy of openframeworks 0.9.3 (the switch to 0.10 will be a lot of work)
* create your ffmpeg linux-64 binaries, you should be able to follow the "windows" instructions almost without change: https://github.com/kritzikratzi/ofxAvCodec/tree/master/ffmpeg_src
* now checkout the miniaudio branch of the oscilloscope with all submodules, and if you're lucky it just works :)

**Comment by s-ol** [comment]
Cool, I will give it a shot some time.

Like the last Linux user in the PR in ofxAvCodec, I am also wondering: do i really need to (re)compile ffmpeg and h264? My OS also provides these libraries (with headers) so unless there is some uncommon configuration or patching going on it shouldn't be necessary.

**Comment by kritzikratzi** [comment]
ffmpeg is continuously changing. if you want to use precompiled version try to find something as close as possible to the commit mentioned in the compilation guide. 

but compiling ffmpeg is not really a big deal, all the configure options are there, and ffmpeg compiles very cleanly. should be done in way under an hour.

**Comment by s-ol** [comment]
@kritzikratzi okay, I'll see how it turns out. I hit another roadblock in the meantime though; openframeworks 0.9 uses an old version of Poco that is incompatible with openssl 1.1.
I already had `openssl-1.0` installed on Arch, and following [this as a guide](https://bbs.archlinux.org/viewtopic.php?pid=1707447#p1707447) I'm *almost* getting `apothecary update poco` to run in `OF/scripts/apothecary`. Change in `OF/scripts/apothecary/formulas/poco/poco.sh`:

    +    PKG_CONFIG_PATH=/usr/lib/openssl-1.0/pkgconfig \
    +    CFLAGS+=" -I/usr/include/openssl-1.0" \
    +    LDFLAGS+=" -L/usr/lib/openssl-1.0 -lssl" \
		./configure $BUILD_OPTS

However it still exits with ` ^ Received error ^` but no error message -.-

**Comment by kritzikratzi** [comment]
oh... i didn't know you have to compile stuff with OF for linux (the windows and osx versions contain all required binary blobs). if you have trouble i can take a look tomorrow...

**Comment by s-ol** [comment]
@kritzikratzi its normal to recompile openFrameworks, but usually poco is precompiled. However there was an ABI update since of0.9 came out. Anyway, I was very close, this is what it actually needs:

    -   local BUILD_OPTS="--no-tests --no-samples --static --omit=CppUnit,CppUnit/WinTestRunner,Data/MySQL,Data/ODBC,PageCompiler,PageCompiler/File2Page,CppParser,PDF,PocoDoc,ProGen"
    +   local BUILD_OPTS="--no-tests --no-samples --static --omit=CppUnit,CppUnit/WinTestRunner,Data/MySQL,Data/ODBC,PageCompiler,PageCompiler/File2Page,CppParser,PDF,PocoDoc,ProGen --include-path=/usr/include/openssl-1.0 --library-path=/usr/lib/openssl-1.0"

        ./configure $BUILD_OPTS

(again, this is for `./apothecary update poco` on ArchLinux with `openssl-1.0` installed; ymmv)

**Comment by s-ol** [comment]
hm... got openframeworks up and running finally (a bit of digital archaeology necessary to bring the version from 2016 up to speed) but now it won't build because of this:

```
Compiling Oscilloscope for Debug
make[1]: Entering directory '/home/s-ol/osc/Oscilloscope'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa gl glu glew gtk+-3.0 libmpg123 
make[1]: execvp: /bin/sh: Argument list too long
make[1]: *** [/home/s-ol/osc/of/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:190: obj/linux64/Debug/.compiler_flags] Error 127
make[1]: Leaving directory '/home/s-ol/osc/Oscilloscope'
make: *** [/home/s-ol/osc/of/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:147: Debug] Error 2
```

**Comment by kritzikratzi** [comment]
did you get it to run on linux after all?

**Comment by s-ol** [comment]
not yet, but haven't had time to try more since my last posts

**Comment by kritzikratzi** [comment]
hey! 

do you hate me if i try to switch over to the latest OF? 
i've given it a shot on osx today, and it's not looking too bad. 
(gotta migrate all the addons too)

**Comment by s-ol** [comment]
@kritzikratzi I would much prefer it actually :) most of my pain came from reviving old of, of 0.10 at least have running already...

**Comment by kritzikratzi** [comment]
:) 

i'm really liking miniaudio, so i'm basing everything off of that branch. 

osx seems to be fine again already, windows is up next. 

i'm thinking linux will have these issues: 

* ofxLibsamplerate misses linux binaries
* ofxNative has no linux implementation 

in a few weeks i can get a linux set up, until then i can only take care of win+mac

**Comment by s-ol** [comment]
>- ofxLibsamplerate misses linux binaries

not really ;)

https://www.archlinux.org/packages/extra/x86_64/libsamplerate/
https://www.archlinux.org/packages/extra/x86_64/libsamplerate/

>- ofxNative has no linux implementation

I might just stub it out and/or implement parts - if I have time to try it at all before you fix it, I have Gamescom and electricity-less vacation coming up in the next weeks...

**Comment by kritzikratzi** [comment]
wehoooo, do your thing, no hurry at all!
:D

**Comment by kritzikratzi** [comment]
closing in favor of #67
