### ISSUE TITLE
"Not a valid Win32 application" error on Windows XP

### ISSUE THREAD

**Issue by RikuKawai** [kritzikratzi/Oscilloscope#50]
I'm trying to run this on Windows XP Home, I have SP3 plus the unofficial SP4 installed.

I can't see any reason why it wouldn't work if it's actually 32-bit as described,

The reason I'm using XP is because this is a rather old PC but it has hardware which can output to a CRT TV.

**Comment by kritzikratzi** [comment]
hi! 

that's correct.  it would maybe theoretically be possible to run on XP, but i'd have to go through quite a bit of pain. 
is there no way you can update your OS? 


best, hansi.

**Comment by RikuKawai** [comment]
This machine would have much difficulty running any newer OS. Specs are Pentium 4 3.2GHz, 2GB DDR 557MHz, GeForce GT 430, Radeon X700 Pro (for composite output). I would also lose my ability to natively play old 16-bit software.

I will try using my other board which has a Phenom II X4 and Windows 10 64-bit as that also has a composite output on the onboard video. If that ends up being too slow (there's no graphics driver for Windows 10), I will try my GTX 280 which is the newest card I have with a TV output.

**Comment by kritzikratzi** [comment]
actually that doesn't sound bad enough, should be easy fast enough for 32bit windows 10. 
i think you should be able to run 16 bit programs through qemu/dosbox. 

anyways, i like the thought of being able to run the oscilloscope down to xp, but it's just too much work for me at the moment. i'm leaving this open though, in case someone else wants to take a stab.

**Comment by Juesto** [comment]
The reason of this is that XP is unsupported.
Compile with VS 2010 compatible compiler.

**Comment by kritzikratzi** [comment]
there is also the `v140_xp` platform toolset to compile for xp in vs15, but i fear it's not as straight forward as switching toolsets.

**Comment by kritzikratzi** [comment]
ok, i'm closing this, because it's too far out for me and no one else has asked for it. if someone wants to work on it, please submit a PR.

**Comment by Juesto** [comment]
@RikuKawai you can actually upgrade your system to Windows 7 32-bits, and still be able to run 16 bits apps.

**Comment by RikuKawai** [comment]
Windows 7 on a Pentium 4 3.2? No thanks.





---- On Wed, 21 Feb 2018 17:23:18 -0500 Juest Zungo &lt;notifications@github.com&gt; wrote ----




@RikuKawai you can actually upgrade your system to Windows 7 32-bits, and still be able to run 16 bits apps.
