### ISSUE TITLE
can't start application

### ISSUE THREAD

**Issue by MPeti1** [kritzikratzi/Oscilloscope#51]
After i try to start it, i can see in task manager Windows Troubleshooter (or something like that, my os is not english) starts, but the oscilloscope not. tried to start in all of the compatibility settings, but no success.
i've tried version 1.0.7, but it's the same. i think the vc lib is installed for me, because visual studio is installed, but to make sure i've ran the installer. it showed me an error (seems like it got bugged again...), but after repair nothing changed, just the installer now shows options for uninstall and repair rather than install (which gave me an error message before repair action), so it seems it's good now.
it would be good if you could do something to display an error message with details of what happened, because if don't needed i don't want to restart my pc, and it's needed to uninstall and install the lib

**Comment by kritzikratzi** [comment]
it sounds like it possible gets stuck opening the soundcard. 

can you double check if your soundcard is set to 44kHz? (that's what it tries to open by default in windows)

**Comment by Juesto** [comment]
Looks like an issue with autodetect and possibly with some device.
Try disabling the automatic feature from settings.txt by setting `AutoDetect=false`

**Comment by MPeti1** [comment]
Sorry for the late response. My sound card is set to 48000 Hz, but now i changed it to 44100 Hz, but that didn't helped. Also tried to set autodetect to false but it's the same. I tried both 1.0.7 and 1.0.8

**Comment by Juesto** [comment]
Sounds like an issue with your sound configuration, do you use multi i/o or aggregators?

**Comment by MPeti1** [comment]
To be honest i don't really know, so probably not. What is multi i/o?
I only have an onboard sound card, but i don't use it because my speakers
are bad. i use my Bluetooth headphones at pc with the help of an
usb-bluetooth stick. Also i recently started to use Viper4Windows (it's a
DSP), but i don't remember if i used it when i opened this issue. Could you
make a debug mode for the application to see what is the problem exactly?

Juest Zungo <notifications@github.com> ezt írta (időpont: 2018. márc. 21.,
Sze 4:51):

**Comment by Juesto** [comment]
Oops about the question.
See #42

**Comment by kritzikratzi** [comment]
closing this, because it's too old and in the new version the audio engine is completely different
