### ISSUE TITLE
[macOS] Move window from scaled monitor to native causes incorrect zoom in app UI

### ISSUE THREAD

**Issue by diimdeep** [kritzikratzi/Oscilloscope#53]
macOS 10.2
1 monitor 2560 x 1600 Retina (scaled as 1280x800)
2 monitor 2560 x 1440 (1:1)
Move window from 1 to 2 causes all interface to scale twice and move to right size
![screen shot 2017-12-05 at 23 33 31](https://user-images.githubusercontent.com/485713/33629375-df047a24-da14-11e7-87df-76575f3c97d6.png)

**Comment by kritzikratzi** [comment]
hey! 

does this fix itself when you change the window size a tiny bit after moving it to another screen? 
simple way out is to disable retina (right click oscilloscope, select "always use low resolution mode" or smthg like that).

**Comment by diimdeep** [comment]
There have to be hook when moving from screen to screen with different scaling https://github.com/openframeworks/openFrameworks/issues/4789#issuecomment-351715114

**Comment by kritzikratzi** [comment]
closing this, because it's not often a problem and it's basically impossible to get right with OF0.9
happy about PRs
