### ISSUE TITLE
Syphon or Spout

### ISSUE THREAD

**Issue by kritzikratzi** [kritzikratzi/Oscilloscope#54]
People really want this. Maybe give it to them.

**Comment by Juesto** [comment]
Syphon is shipped with OBS Studio, no idea about Spout
what's the plan/idea if any?

**Comment by kritzikratzi** [comment]
the other way around, for instance to act as a source for obs studio (or any other application that supports it)

**Comment by ffd8** [comment]
Give the masses what they want! √ for adding Syphon!

**Comment by kritzikratzi** [comment]
okay... i'll put it in the next version!

**Comment by kritzikratzi** [comment]
implemented, will be in the next release
