### ISSUE TITLE
[1.0.9 mac] GUI doesn't autohide

### ISSUE THREAD

**Issue by Juesto** [kritzikratzi/Oscilloscope#56]
gui does show up properly when mouse goes over.
however it does not hide whenever the mouse is still or outside of the area.

EDIT: huh actually looks like there is a visual feature that for some reason it wasnt working properly

**Comment by ffd8** [comment]
Old issue, but @Juesto I had the same issue, then @kritzikratzi  told me about pressing `Tab` to toggle the GUI.

**Comment by Juesto** [comment]
yeah but it persists and does not hide when tab is pressed, it's a oddball
