### ISSUE TITLE
windows 10 - black window

### ISSUE THREAD

**Issue by jaydenrre** [kritzikratzi/Oscilloscope#60]
Hi,

I cant get the program to run, which is odd since I have used this software before on this very same computer before.  I have changed hard drives and reinstalled W10 since the last time I used it.  Now when I run the exe I just get a black window. No error msg or anything.  Tried 1.0.8, .7, and .6 and get the exact same error.

Tried switching autodetect in the txt settings to off, saw that as a possible solution in another thread but it changed nothing.

Any advice?

**Comment by jaydenrre** [comment]
With all versions this is all I get. No play, no icons nothing.

![image](https://user-images.githubusercontent.com/22672733/49325110-8b875d00-f4f1-11e8-8916-5ab084cc2c7d.png)

**Comment by kritzikratzi** [comment]
ah, that looks a bit more serious. 

if you press `tab` also nothing?

**Comment by jaydenrre** [comment]
just tried it. tab does nothing

**Comment by kritzikratzi** [comment]
your computer is fucked :D

**Comment by kritzikratzi** [comment]
closing because it looks like a graphics driver issue, and there's not much i can do.
