### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by versipellis** [kritzikratzi/Oscilloscope#61]
Hey! I love the visuals that this oscilloscope produces. Is there a paper for the algorithm or details on the algo anywhere I can read up on? I have some thoughts for a future project I would love to be able to use this in (with credits attributed to the appropriate sources, of course).

Thanks in advance!

**Comment by kritzikratzi** [comment]
m1el wrote a good introduction: http://m1el.github.io/woscope-how/

**Comment by versipellis** [comment]
Thank you!
