### ISSUE TITLE
Use with internal soundcard

### ISSUE THREAD

**Issue by sonicuse** [kritzikratzi/Oscilloscope#62]
Hello , i just want to know if it is possible to use it with just the internal soundcard of a macbook with vcv rack for example.
Ive tried with sunflower but no success. The audio doesn’t get to the scope. I would be happy about any help.
Update : Ive Tryed to use it with an RME UCX Soundcard all set to 44.1.
it doesnt take any input.not in version 10.9/10.7./10.6
it remains black
Merci

**Comment by kritzikratzi** [comment]
hey

closing this, because it looks like the switch to miniaudio is staying around, so all the audio i/o bugs will be new and different :)

**Comment by sonicuse** [comment]
i have realy no idea what that means?
switch to miniaudio ???



Am 15.08.2019 um 08:12 schrieb hansi raber:

> miniaudio
