### ISSUE TITLE
Scrolling list of audio inputs

### ISSUE THREAD

**Issue by ffd8** [kritzikratzi/Oscilloscope#63]
When pressing the MIC icon, a popup of just 5 audio input devices are listed. Seems reasonable, unless someone has a longer list of options from various audio devices (virtual stereo pairs from multi-channel devices) – or as I recently learned on a students computer, Adobe is also adding a few audio devices with some software. This list can get long – so a scrollable list would be awesome to reach them all.

**Comment by kritzikratzi** [comment]
latest version does this, which is hopefully ok too: 

![image](https://user-images.githubusercontent.com/96657/157456116-71ce0302-f792-4b41-80fe-472905df4de7.png)
