### ISSUE TITLE
Feature Request: Dither Toggling

### ISSUE THREAD

**Issue by Some1NamedNate** [kritzikratzi/Oscilloscope#69]
When playing back oscilloscope music (from Jerobeam Fenderson, Chris Allen et. al.) with dithering enabled, there are certain times when, say, a cube's edges are presented to be not straight. This is the case for ["Oscillofun" by Atom Delta](https://demozoo.org/productions/172382/).

**Comment by kritzikratzi** [comment]
dithering is a fixed point problem, but i'm using floating point representation so i don't see how it applies. 
if you could send a comparison image i can maybe figure it out.

**Comment by kritzikratzi** [comment]
closing, never heard back
