### ISSUE TITLE
Issue Using Secondary Audio Device

### ISSUE THREAD

**Issue by Robonics** [kritzikratzi/Oscilloscope#70]
I have a Corsair Void Elite Pro Wireless plugged into my PC and set as my Primary audio device. In any other application it works fine, however Oscilloscope refuses to play through my headset. I've tried manually setting the Headset as my Audio Device and restarting the program and nothing has worked.

**Comment by kritzikratzi** [comment]
please be more detailed in future bug reports. i know nothing about your audio setup, your operating system or the oscilloscope version you used. 

anyways, closing this because the audio driver is changing soon  (i can send you a copy of the test version if you want)
