### ISSUE TITLE
Linux (Arch/Manjaro) compilation issues

### ISSUE THREAD

**Issue by sxiii** [kritzikratzi/Oscilloscope#71]
Greetings.

Trying to build the project for Manjaro 20 (arch-based distro).

After make:
```
Makefile:20: ../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk: No such file or directory
make: *** No rule to make target '../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk'.  Stop.
```
Any hints? Thanks.

**Comment by kritzikratzi** [comment]
maybe wrong openframeworks version? 
this is for 0.10.1 https://openframeworks.cc/versions/v0.10.1/

**Comment by s-ol** [comment]
If you want to clone it elsewhere, uncomment.& adjust `OF_ROOT` in [config.make:11](https://github.com/kritzikratzi/Oscilloscope/blob/master/config.make#L11)

**Comment by kritzikratzi** [comment]
@s-ol wow, didn't know that variable is finally there, so good!

**Comment by kritzikratzi** [comment]
@sxiii did you manage to compile it?

**Comment by sxiii** [comment]
> @sxiii did you manage to compile it?

Ahh okay so I've done the following:
1) `wget https://openframeworks.cc/versions/v0.10.1/of_v0.10.1_linux64gcc6_release.tar.gz`
2) `tar -xvzf of*gz`
3) `mv of* openframeworks`
4) `mv Oscilloscope openframeworks/apps/myApps/Oscilloscope`
5) `cd openframeworks/apps/myApps/Oscilloscope && make`

Now it's compiling. I'll update this message after it completes. Thanks for your help @kritzikratzi and @s-ol

**Comment by s-ol** [comment]
@sxiii any particular reason you are not using openframeworks from the AUR? Looks like you are dealing with dependency issues, the package should help with that. Also note that openFrameworks comes with installation scriptd that it looks like you haven't been running: https://openframeworks.cc/setup/linux-install/

**Comment by kritzikratzi** [comment]
@sxiii yep, please follow the install instructions / use the scripts bundled with OF, otherwise you will suffer horribly

**Comment by sxiii** [comment]
> @sxiii any particular reason you are not using openframeworks from the AUR? Looks like you are dealing with dependency issues, the package should help with that. Also note that openFrameworks comes with installation scriptd that it looks like you haven't been running: https://openframeworks.cc/setup/linux-install/

No, there's no particular reason. In AUR, however, I do have a newer version 0.11, while @kritzikratzi recommended v 0.10 earlier. But anyways, here's doing it with `pikaur -S openframeworks`:
```
Compiling projectGenerator for Release
Linking bin/projectGenerator for linux64
/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../lib/Scrt1.o:init.c:function _start: error: undefined reference to 'main'
collect2: error: ld returned 1 exit status
make[1]: *** [/home/sw/.cache/pikaur/build/openframeworks/src/of_v0.11.0_linux64gcc6_release/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:405: bin/projectGenerator] Error 1
make: *** [/home/sw/.cache/pikaur/build/openframeworks/src/of_v0.11.0_linux64gcc6_release/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2
==> ERROR: A failure occurred in build().
```

I will try to follow the setup steps from the link manually and update here if I succeeded or not. :)

**Comment by s-ol** [comment]
@sxiii maybe that would be a good idea, so far it looks more like you are having problems installing openFrameworks rather than this project. Sadly that's pretty common, I also had to fight it for a long time and I dread upgrading it every time :(

**Comment by kritzikratzi** [comment]
@sxiii i'm only using it on ubuntu, so i can't really say much about compiling on arch. 

either way, you never need to call compileOF.sh manually. instead clone the oscilloscope project into `openframeworks/apps/myApps/oscilloscope` and run `make -j8 && make run` there.

**Comment by sxiii** [comment]
@kritzikratzi but Oscilloscope won't work without OF and I don't have OF installed or compiled (it does not compile neither from AUR repos nor from sources according to official documentation)? So what do you mean by "you never need to call compileOF.sh manually"? :)

**Comment by kritzikratzi** [comment]
ok, so there are at least two problems: 

>     [sw@t490s archlinux]$ sudo ./install_dependencies.sh
>     ...
>     sed: can't read /addons/ofxOpenCv/addon_config.mk: No such file or directory
>     sed: can't read /addons/ofxOpenCv/addon_config.mk: No such file or directory

i'm guessing you are using this install script: https://github.com/openframeworks/openFrameworks/blob/patch-release/scripts/linux/archlinux/install_dependencies.sh#L13-L32

there the `$ROOT` variable seems empty. you could run this instead `sudo ROOT=. ./install_dependencies.sh`, but ... 



then there is the other error. i glanced over it a bit quickly, compileOF.sh will be called as part of the oscilloscope make file. it's an OF error at this point (eg those problems don't exist on ubuntu as far as i can tell). do you get better errors with  `make VERBOSE=1` or `make -n` or something like that? maybe i can help, but maybe not tbh
