### ISSUE TITLE
libusb unresolved external symbol 

### ISSUE THREAD

**Issue by AndnixSH** [kritzikratzi/Oscilloscope#73]
Trying to compile myself, just to see if the latest commit has solved my issues. But i ended up with the unresolved external symbol errors with libusb. Any idea what's the cause?

![image](https://user-images.githubusercontent.com/40742924/110132794-d593d300-7dcb-11eb-9180-1917ba7ccffd.png)

**Comment by kritzikratzi** [comment]
it means the libusb-1.0.lib wasn't found correctly. 

i assume you went for a 32 bit build, but only 64 bit is supported!
