### ISSUE TITLE
Dependency rot on Linux (old dependencies libavcodec.so.56 and libva.so.1 need to be manually symlinked)

### ISSUE THREAD

**Issue by TransLillie** [kritzikratzi/Oscilloscope#74]
On Manjaro 12.1.2 Pahvo, dependency rot is occurring. `/usr/lib/libva.so.2` needs to be symlinked to `/usr/lib/libva.so.1`, and `/usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56` needs to be symlinked to `/usr/lib/x86_64-linux-gnu/libavcodec.so.56` otherwise the program will crash.

**Comment by DominikNovosel** [comment]
Same thing occurs on OpenSUSE Leap 15.2.

**Comment by Ivy2345** [comment]
The provided Linux build is a few releases old though so it needs updating.

**Comment by kritzikratzi** [comment]
the idea is to build ffmpeg yourself and include the result the program (it's mentioned in the build instructions). 

if someone wants to make a build a deb/rpm/... bundle that depends on a ffmpeg installed with the system, then please go ahead. but this is more work than i have time for.
