### ISSUE TITLE
(windows) audio not playing/loading

### ISSUE THREAD

**Issue by shamshitty** [kritzikratzi/Oscilloscope#75]
so I've only just had this problem today. audio won't play or just doesn't seem to load as when I import a wave file, the default konichiwa wav file appears. but even that doesn't play, it's only visible if I scroll through the progress bar(?).
I've tried reinstalling the program but that didn't fix it.

https://user-images.githubusercontent.com/68004605/135502146-ec0e55aa-8cea-4074-8029-b46c5f803f69.mp4

**Comment by Juesto** [comment]
Try using the previous version or uninstall ASIO.

**Comment by kritzikratzi** [comment]
i finally released 1.1.0, can you check if this fixes the issue?

**Comment by GucciFlipFlops1917** [comment]
Beautiful. Thanks!

**Comment by kritzikratzi** [comment]
great!
