### ISSUE TITLE
[1.1.0 windows] no render if input device doesn't support rate, loopback doesn't work

### ISSUE THREAD

**Issue by Juesto** [kritzikratzi/Oscilloscope#82]
i have virtual audio cable for input loopback on windows.
i do not have the 22.5khz rate set up there causing no output/rendering on the app.
loopback doesn't enter the mic input mode at all but rather it stays in paused playback.

**Comment by kritzikratzi** [comment]
i'm a bit puzzled ... where do the 22.5 kHz come from?

**Comment by Juesto** [comment]
Not sure about that, sorry.

**Comment by Juesto** [comment]
I don't remember and I am not on my installation at the moment
